### ISSUE TITLE
Url fragment/hash with leading integer

### ISSUE THREAD

**Issue by EtunaAikido** [mavoweb/mavo#220]
Create a page with Mavo, index.html, then try to load index.html#1. This gives an error. #a1 or #a works fine, while #1a fails as well, so it's the leading integer that's the problem.

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#1a' is not a valid selector.
    at https://get.mavo.io/mavo.js:1:987
    at HTMLHtmlElement.document.documentElement.addEventListener.evt (https://get.mavo.io/mavo.js:1365:25)
    at HTMLHeadingElement.fire (https://get.mavo.io/mavo.js:1:6185)
    at Object.function.n.type.r.element.n.Element.n.Element.(anonymous function) (https://get.mavo.io/mavo.js:1:8470)
    at Function.function.n.type.r.$.n.(anonymous function) [as fire] (https://get.mavo.io/mavo.js:1:8858)
    at e.dataChanged (https://get.mavo.io/mavo.js:2746:5)
    at e.dataChanged (https://get.mavo.io/mavo.js:3931:33)
    at sneak (https://get.mavo.io/mavo.js:3923:10)
    at e.sneak (https://get.mavo.io/mavo.js:1216:15)
    at Function.sneak (https://get.mavo.io/mavo.js:1233:31)
```

**Comment by LeaVerou** [comment]
Yup, this is a bug. Should be very easy to fix though, we just need to use `getElementById` instead of `querySelector`.

**Comment by LeaVerou** [comment]
Could you please check that this is fixed now?

**Comment by EtunaAikido** [comment]
Can confirm, works fine now.
